# -------- WARNING ---------
# Your config does not conform to the schema.
# Violations are listed below:
# 
# ERROR IN CONFIG FILE:
# [#] required key [version] not found
jobs:
  build:
    docker:
    - image: python:3.7.9
    working_directory: ~/repo
    steps:
    - checkout
    - run: ls && echo "chechout cast repo"
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          make install
          # Install hadolint
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.18.0/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: run lint
        command: ". venv/bin/activate\nmake lint           \n"
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/CircleCI-Public/circleci-cli/compare/e72d9bf5074d5d30bffdc82a219658a02d428784...e72d9bf5074d5d30bffdc82a219658a02d428784
workflows:
  version: 2
  workflow:
    jobs:
    - build
